DROP TABLE TRANSACTIONS;
DROP TABLE ACCOUNT;
DROP TABLE CUSTOMER;
DROP TABLE DELETED_ACCOUNTS;


CREATE TABLE CUSTOMER(
fname VARCHAR(50) NOT NULL,
lname VARCHAR(50) NOT NULL,
mname VARCHAR(50),
street VARCHAR(150) NOT NULL,
city VARCHAR (100) NOT NULL,
state VARCHAR (100) NOT NULL,
zip VARCHAR(5) NOT NULL,
phone VARCHAR(10) NOT NULL,
email VARCHAR(150) NOT NULL,
username VARCHAR(10) NOT NULL UNIQUE,
password VARCHAR(15) NOT NULL,
id int GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY
);

CREATE TABLE ACCOUNT(
type VARCHAR(30) NOT NULL,
description VARCHAR(100),
balance DEC(13,2) DEFAULT 0,
begin_Bal DEC(13,2),
credit_Lim DEC(13,2) DEFAULT 0, 
cust_Id int NOT NULL,
time_Stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
acc_Num int NOT NULL UNIQUE,
status VARCHAR(10) NOT NULL,
id int GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY
);

CREATE TABLE TRANSACTIONS(
time_Stamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
type VARCHAR(10) NOT NULL,
amount DEC(13,2) NOT NULL,
balance DEC(13,2) NOT NULL,
description VARCHAR(100),
id int GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
acc_Id int NOT NULL
);

CREATE TABLE DELETED_ACCOUNTS(
type VARCHAR(30) NOT NULL,
status VARCHAR(100) NOT NULL,
description VARCHAR(100),
cust_Id int NOT NULL,
opened_Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
closed_Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
acc_Num int NOT NULL UNIQUE,
id int GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY
);

--ALTER TABLE CUSTOMER ON DELETE CASCADE;
ALTER TABLE ACCOUNT ADD FOREIGN KEY (cust_Id) REFERENCES CUSTOMER (id);
ALTER TABLE TRANSACTIONS ADD FOREIGN KEY (acc_Id) REFERENCES ACCOUNT (id) ON DELETE CASCADE;
ALTER TABLE DELETED_ACCOUNTS ADD FOREIGN KEY (cust_Id) REFERENCES CUSTOMER (id);

INSERT INTO CUSTOMER (fname, lname, street, city, state, zip, phone, email, username, password) VALUES
    ('Eduardo', 'Lopez', '3210 Caleb DR', 'Austin', 'TX', '78725', '5129144856', 'lpz_lalo@yahoo.com', 'admin', 'admin');